### ISSUE TITLE
latest search backend breaks search functionality

### ISSUE THREAD

**Issue by tngTUDOR** [brightway-lca/brightway2-ui#45]
yep, so it seems.

## Current

search by category breaks the app

```
snoopb-ei310-sample@(biosphere3) >> s -cat {air} Ammonia
Filtering for category air after search
Traceback (most recent call last):
  File "/home/pizamonday/.local/bin/bw2-browser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pizamonday/.local/lib/python3.12/site-packages/bw2ui/bin/bw2_browser.py", line 1619, in main
    activitybrowser.cmdloop()
  File "/usr/lib64/python3.12/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/home/pizamonday/.local/lib/python3.12/site-packages/bw2ui/bin/bw2_browser.py", line 1191, in do_s
    results = Database(self.database).search(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pizamonday/.local/lib/python3.12/site-packages/bw2data/backends/base.py", line 972, in search
    results = s.search(string=string, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pizamonday/.local/lib/python3.12/site-packages/bw2data/search/search.py", line 77, in search
    results = self.index.search(string, weights=boosts, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pizamonday/.local/lib/python3.12/site-packages/bw2data/search/indices.py", line 181, in search
    *self._process_condition(filter, filter_entity)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pizamonday/.local/lib/python3.12/site-packages/bw2data/search/indices.py", line 162, in _process_condition
    raise ValueError("unsupported argument type: {}".format(type(v)))
ValueError: unsupported argument type: <class 'list'>

```

**Comment by tngTUDOR** [comment]
as of 0.40.0 can't reproduce (myself, obvi) so closing
